# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_chains_to_measure_as_list_ <- function(c_chains, k, m) {
    .Call('_unbiasedpoisson_c_chains_to_measure_as_list_', PACKAGE = 'unbiasedpoisson', c_chains, k, m)
}

estimator_bin_ <- function(c_chains, component, lower, upper, k, m, lag) {
    .Call('_unbiasedpoisson_estimator_bin_', PACKAGE = 'unbiasedpoisson', c_chains, component, lower, upper, k, m, lag)
}

fcprd <- function(X) {
    .Call('_unbiasedpoisson_fcprd', PACKAGE = 'unbiasedpoisson', X)
}

cpp_prod <- function(X, Y) {
    .Call('_unbiasedpoisson_cpp_prod', PACKAGE = 'unbiasedpoisson', X, Y)
}

multinomial_resampling_n_ <- function(weights, ndraws) {
    .Call('_unbiasedpoisson_multinomial_resampling_n_', PACKAGE = 'unbiasedpoisson', weights, ndraws)
}

fast_rmvnorm_ <- function(nsamples, mean, covariance) {
    .Call('_unbiasedpoisson_fast_rmvnorm_', PACKAGE = 'unbiasedpoisson', nsamples, mean, covariance)
}

fast_rmvnorm_cholesky_ <- function(nsamples, mean, cholesky) {
    .Call('_unbiasedpoisson_fast_rmvnorm_cholesky_', PACKAGE = 'unbiasedpoisson', nsamples, mean, cholesky)
}

fast_dmvnorm_ <- function(x, mean, covariance) {
    .Call('_unbiasedpoisson_fast_dmvnorm_', PACKAGE = 'unbiasedpoisson', x, mean, covariance)
}

fast_dmvnorm_cholesky_inverse_ <- function(x, mean, cholesky_inverse) {
    .Call('_unbiasedpoisson_fast_dmvnorm_cholesky_inverse_', PACKAGE = 'unbiasedpoisson', x, mean, cholesky_inverse)
}

rmvnorm_max_coupling_ <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_unbiasedpoisson_rmvnorm_max_coupling_', PACKAGE = 'unbiasedpoisson', mu1, mu2, Sigma1, Sigma2)
}

rmvnorm_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_unbiasedpoisson_rmvnorm_max_coupling_cholesky', PACKAGE = 'unbiasedpoisson', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

rmvnorm_reflection_max_coupling_ <- function(mu1, mu2, Sigma_chol, inv_Sigma_chol) {
    .Call('_unbiasedpoisson_rmvnorm_reflection_max_coupling_', PACKAGE = 'unbiasedpoisson', mu1, mu2, Sigma_chol, inv_Sigma_chol)
}

prune_measure_ <- function(df) {
    .Call('_unbiasedpoisson_prune_measure_', PACKAGE = 'unbiasedpoisson', df)
}

systematic_resampling_n_ <- function(weights, ndraws, u) {
    .Call('_unbiasedpoisson_systematic_resampling_n_', PACKAGE = 'unbiasedpoisson', weights, ndraws, u)
}

