# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_chains_to_measure_as_list_ <- function(c_chains, k, m) {
    .Call('_umcmchandbook_c_chains_to_measure_as_list_', PACKAGE = 'umcmchandbook', c_chains, k, m)
}

estimator_bin_ <- function(c_chains, component, lower, upper, k, m, lag) {
    .Call('_umcmchandbook_estimator_bin_', PACKAGE = 'umcmchandbook', c_chains, component, lower, upper, k, m, lag)
}

fast_rmvnorm_ <- function(nsamples, mean, covariance) {
    .Call('_umcmchandbook_fast_rmvnorm_', PACKAGE = 'umcmchandbook', nsamples, mean, covariance)
}

fast_rmvnorm_cholesky_ <- function(nsamples, mean, cholesky) {
    .Call('_umcmchandbook_fast_rmvnorm_cholesky_', PACKAGE = 'umcmchandbook', nsamples, mean, cholesky)
}

fast_dmvnorm_ <- function(x, mean, covariance) {
    .Call('_umcmchandbook_fast_dmvnorm_', PACKAGE = 'umcmchandbook', x, mean, covariance)
}

fast_dmvnorm_cholesky_inverse_ <- function(x, mean, cholesky_inverse) {
    .Call('_umcmchandbook_fast_dmvnorm_cholesky_inverse_', PACKAGE = 'umcmchandbook', x, mean, cholesky_inverse)
}

rmvnorm_max_coupling_ <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_umcmchandbook_rmvnorm_max_coupling_', PACKAGE = 'umcmchandbook', mu1, mu2, Sigma1, Sigma2)
}

rmvnorm_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_umcmchandbook_rmvnorm_max_coupling_cholesky', PACKAGE = 'umcmchandbook', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

rmvnorm_reflection_max_coupling_ <- function(mu1, mu2, Sigma_chol, inv_Sigma_chol) {
    .Call('_umcmchandbook_rmvnorm_reflection_max_coupling_', PACKAGE = 'umcmchandbook', mu1, mu2, Sigma_chol, inv_Sigma_chol)
}

